In [2]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

print(torch.__version__)

2.0.1+cu118


In [12]:
# scalar

scalar = torch.tensor(7)
scalar

tensor(7)

In [13]:
scalar.ndim

0

In [15]:
# Get tensor back as Python int

scalar.item()

7

In [16]:
# Vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [17]:
vector.ndim

1

In [18]:
vector.shape

torch.Size([2])

In [19]:
# MATRIX
matrix = torch.tensor([[7, 8],
                       [9, 10]])
matrix

tensor([[ 7,  8],
        [ 9, 10]])

In [20]:
matrix.ndim

2

In [22]:
matrix[1]

tensor([ 9, 10])

In [23]:
matrix.shape

torch.Size([2, 2])

In [28]:
# TENSOR
tensor = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]]])
tensor

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [25]:
tensor.ndim

3

In [26]:
tensor.shape

torch.Size([1, 3, 3])

In [29]:
tensor[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

### Random tensors

In [67]:
# Create a random tensor of size (3, 4)
random_tensor = torch.rand(1, 3, 4)

In [68]:
random_tensor

tensor([[[0.6794, 0.5770, 0.4984, 0.2264],
         [0.5074, 0.5622, 0.9071, 0.3708],
         [0.3307, 0.8726, 0.6524, 0.8919]]])

In [69]:
random_tensor.ndim

3

In [71]:
random_image_size_tensor = torch.rand(size=(3, 224, 224))
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

### Zeros and one

In [75]:
# Create a tensor of all zeros
zeros = torch.zeros(size=(3, 4))
zeros, zeros.dtype

(tensor([[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]),
 torch.float32)

In [74]:
# Create a tensor of all ones
ones = torch.ones(size=(3, 4))
ones, ones.dtype

#data type is float

(tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]),
 torch.float32)

### Creating a range tensors and tensors-list

In [81]:
# Use torch.range()
one_to_ten1=torch.arange(0, 10)

one_to_ten2=torch.arange(start=0, end=10)

one_to_ten3=torch.arange(start=0, end=100, step=7)

one_to_ten1,one_to_ten2,one_to_ten3

(tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 tensor([ 0,  7, 14, 21, 28, 35, 42, 49, 56, 63, 70, 77, 84, 91, 98]))

In [85]:
# Creating tensors list
ten_zeros = torch.zeros_like(input=one_to_ten1)
ten_ones = torch.ones_like(input=one_to_ten1)

ten_zeros, ten_ones

(tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0]),
 tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1]))

### Tensor datatypes

**Note:** 3 big errors usually run into with PyTorch

1. datatype
2. shape
3. not on right device

In [97]:
# Float 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None,
                               device=None,
                               requires_grad=False)
float_32_tensor, float_32_tensor.dtype

(tensor([3., 6., 9.]), torch.float32)

In [98]:
float_32_tensor.dtype

torch.float32

In [99]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [103]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

In [112]:
int_32_tensor = torch.tensor([3, 6, 9], dtype=torch.long)
int_32_tensor

tensor([3, 6, 9])

In [113]:
float_32_tensor * int_32_tensor

tensor([ 9., 36., 81.])

### Getting information from tensors

1. Tensors not right datatype - `tensor.dtype`
2. Tensors not right shape - `tensor.shape`
3. Tensors not right device - `tensor.device`

In [114]:
# Create a tensor
some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.3997, 0.0042, 0.1363, 0.3327],
        [0.9842, 0.8964, 0.8548, 0.4995],
        [0.3892, 0.0315, 0.4115, 0.5214]])

In [116]:
# Find out details about som tensor
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device of tensor: {some_tensor.device}")

tensor([[0.3997, 0.0042, 0.1363, 0.3327],
        [0.9842, 0.8964, 0.8548, 0.4995],
        [0.3892, 0.0315, 0.4115, 0.5214]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device of tensor: cpu


### Manipulating Tensors (tensor operations)

Tensor operations include:
* Addition
* Subtraction
* Multiplication (element-wise)
* ZeroDivisionError Matrix multiplication

In [117]:
# Create a tensor and add 10 to it
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [118]:
# Multiply tensor by 10
tensor = tensor * 10
tensor

tensor([10, 20, 30])

In [119]:
torch.mul(tensor, 10)

tensor([100, 200, 300])

### Matrix multiplication

Two main ways of performing multiplication in neural networks and deep learning:

1. Element-wise multiplication
2. Matrix multiplication

In [121]:
# Element wise multiplication
print(tensor, "*", tensor)
print(f"Equals: {tensor * tensor}")

tensor([10, 20, 30]) * tensor([10, 20, 30])
Equals: tensor([100, 400, 900])


In [122]:
# Matrix multiplication
torch.matmul(tensor, tensor)

tensor(1400)

In [137]:
tensor_B = torch.tensor([[7, 10],
                         [8, 11],
                         [9, 12]])

torch.matmul(tensor_B, torch.transpose(tensor_B, 0, 1))

tensor([[149, 166, 183],
        [166, 185, 204],
        [183, 204, 225]])

### Finding the min, max, mean, sum, etc(tensor aggregation)

In [138]:
# Create a tensor
x = torch.arange(0, 100, 10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [146]:
# Finding the min, max, mean
torch.min(x), x.min(), torch.max(x), x.max(), torch.mean(x.type(torch.float64)), x.type(torch.float64).mean()

(tensor(0),
 tensor(0),
 tensor(90),
 tensor(90),
 tensor(45., dtype=torch.float64),
 tensor(45., dtype=torch.float64))

In [147]:
# Finding the sum
torch.sum(x), x.sum()

(tensor(450), tensor(450))

## Finding the positional min and max

In [148]:
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [150]:
# Finding the position(index) in tensor that has the minimum value 
x.argmin(), x.argmax()

(tensor(0), tensor(9))