### Reshaping, stacking, squeezing and unsqueezing tensors

* Reshaping - reshapes an input tensor to a defined shape
* View - return a view of an input tensor of certain shape but keep the same memory as the original tensor
* Stacking - combine multiple tensors on top of each other (vstack) or side by side(hstack)
* Squeeze - removes all `1` dimensions from a tensor
* Unsqueeze - add all `1` dimensions to a target tensor
* Permute - Return a view of the input with dimensions permuted (swapped) in a certain way

In [43]:
import torch
x = torch.arange(1., 10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [44]:
# Add an extra dimension
x_reshaped = x.reshape(1,1,9)
x_reshaped, x_reshaped.shape

(tensor([[[1., 2., 3., 4., 5., 6., 7., 8., 9.]]]), torch.Size([1, 1, 9]))

In [45]:
# Change the view
z = x.view(1,1,9)
z, z.shape

(tensor([[[1., 2., 3., 4., 5., 6., 7., 8., 9.]]]), torch.Size([1, 1, 9]))

In [46]:
# Changing z changes x because they use the same address of the memory
z[:, :, 0] = 7 # :는 하나의 차원을 그대로 받음을 뜻함
z, x

(tensor([[[7., 2., 3., 4., 5., 6., 7., 8., 9.]]]),
 tensor([7., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [47]:
# Stack tensors on top of each other
x_stacked = torch.stack([x, x, x, x], dim=0)
x_stacked

tensor([[7., 2., 3., 4., 5., 6., 7., 8., 9.],
        [7., 2., 3., 4., 5., 6., 7., 8., 9.],
        [7., 2., 3., 4., 5., 6., 7., 8., 9.],
        [7., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [51]:
# torch.squeeze() - removes all single dimensions from a target tensor
print(f"Previous tensor: {x_reshaped}")
print(f"Previous shape: {x_reshaped.shape}")

# Remove extra dimensions from x_reshaped
x_squeezed = x_reshaped.squeeze()
print(f"\nNew tensor: {x_squeezed}")
print(f"New shape: {x_squeezed.shape}") # 1차원 다 사라짐

Previous tensor: tensor([[[7., 2., 3., 4., 5., 6., 7., 8., 9.]]])
Previous shape: torch.Size([1, 1, 9])

New tensor: tensor([7., 2., 3., 4., 5., 6., 7., 8., 9.])
New shape: torch.Size([9])


In [63]:
# torch.unsqueeze() - adds a single dimension to a target tensor at a specific dim
print(f"Previous target: {x_squeezed}")
print(f"Previous shape: {x_squeezed.shape}")

x_unsqueezed = x_squeezed.unsqueeze(dim=0) # 인자 dim은 1차원이 들어갈 인덱스
print(f"\nNew tensor: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")
x_unsqueezed = x_unsqueezed.unsqueeze(dim=2)
print(f"\nNew tensor: {x_unsqueezed.unsqueeze(dim=1)}")
print(f"New shape: {x_unsqueezed.shape}")

Previous target: tensor([7., 2., 3., 4., 5., 6., 7., 8., 9.])
Previous shape: torch.Size([9])

New tensor: tensor([[7., 2., 3., 4., 5., 6., 7., 8., 9.]])
New shape: torch.Size([1, 9])

New tensor: tensor([[[[7.],
          [2.],
          [3.],
          [4.],
          [5.],
          [6.],
          [7.],
          [8.],
          [9.]]]])
New shape: torch.Size([1, 9, 1])


In [67]:
# torch.permute - reaaranges the dimensions of a target tensor in a specified order
x_original = torch.rand(size=(224, 112, 3))

# Permute the original
x_permuted = x_original.permute(1, 0, 2) # 1->0, 0->1, 2->2

print(f"Previous shape: {x_original.shape}")
print(f"New shape: {x_permuted.shape}")

Previous shape: torch.Size([224, 112, 3])
New shape: torch.Size([112, 224, 3])


## Indexing(selecting data from tensors)


In [68]:
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [71]:
x[0, 0]

tensor([1, 2, 3])

In [78]:
x[0,:,0:2]

tensor([[1, 2],
        [4, 5],
        [7, 8]])